### ISSUE TITLE
[CONTENT] Change tutorial Babel dependency to YAML files 

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#3165]
**Describe the issue**
I would like to propose to change the current Babel dependency for the tutorial into a YAML file one. With #3163 in mind we will have a rapidly growing amount of translations to handle for the tutorials. This is fine, except it will be hard to keep this nice and structured through Babel. By using a YAML file we can use this to approach the tutorials similar to the adventures using a structure somewhat like this:

```
intro:
  steps:
    1:
      title: ...
      step: ...
    2:
      title: ...
      step: ...
teacher:
  steps:
    1:
      title: ...
      step: ...
    2:
      title: ...
      step: ...
levels:
  1:
    steps:
      1:
        title: ...
        step: ...
      2:
        title: ...
        step: ...
```

We have to have a dedicated section for both the intro and teacher tutorials as they are not level-dependent. What do you think @Felienne @Mark-Giesen ?

**Edit**
This change has the added advantage that we can cache all language / keyword language combinations such as we do with the adventures. Speeding up our user experience significantly including the dynamic keywords.
